# Generated by Django 5.2.5 on 2025-10-05 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción del producto')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones del producto')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio del producto')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subcatalogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del subcatálogo')),
                ('descripcion', models.TextField(verbose_name='Descripción del subcatálogo')),
                ('productos', models.ManyToManyField(to='product_view.producto')),
            ],
            options={
                'verbose_name': 'Subcatálogo',
                'verbose_name_plural': 'Subcatálogos',
                'db_table': 'subcatalogos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('subcatalogos', models.ManyToManyField(to='product_view.subcatalogo')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'db_table': 'catalogos',
                'ordering': ['nombre'],
            },
        ),
    ]
